### ISSUE TITLE
python setup.py install  :Installtion failure on Windows

### ISSUE THREAD

**Issue by cxxun** [Radiomics/pyradiomics#308]
Like this

```
D:\Anaconda2\python.exe F:/pyradiomics-master/setup.py
Traceback (most recent call last):
  File "F:/pyradiomics-master/setup.py", line 69, in <module>
    version=versioneer.get_version(),
  File "F:\pyradiomics-master\versioneer.py", line 1476, in get_version
    return get_versions()["version"]
  File "F:\pyradiomics-master\versioneer.py", line 1408, in get_versions
    cfg = get_config_from_root(root)
  File "F:\pyradiomics-master\versioneer.py", line 342, in get_config_from_root
    parser = configparser.SafeConfigParser()
AttributeError: 'module' object has no attribute 'SafeConfigParser'

Process finished with exit code 1
```

**Comment by jcfr** [comment]
Can you try to install the module `configparser` first and check if you still have an error ?
