### ISSUE TITLE
Problem in Feature Extraction after Pulling Changes

### ISSUE THREAD

**Issue by tommydino93** [Radiomics/pyradiomics#371]
Hi @JoostJM  @fedorov, Sorry to bother you again but this time I'm really desperate!
I was calculating all features, both from the original image and from the Wavelet filtered image and it worked fine.

Since I also wanted to extract features from the 2DLBP image, I simply tried writing: `imageoperations.getLBP2DImage` but the `getLBP2DImage` method wasn't recognized. So I figured that since you had added that method later to the repository, I just had to syncronize my package in PyCharm. So what I did was: VCS>Git>Pull in PyCharm following [this guide](https://www.jetbrains.com/help/pycharm/sync-with-a-remote-repository.html). 

The problem is that now the **very same** code that was running perfectly before throws me this error which I can't understand:

```
FAILED: Traceback (most recent call last):
  File "D:\Getting_Started_PyCharm\Pyradiomics\radiomics\base.py", line 162, in calculateFeatures
    self.featureValues[feature] = getattr(self, 'get%sFeatureValue' % feature)()
  File "D:\Getting_Started_PyCharm\Pyradiomics\radiomics\shape.py", line 337, in getMaximum2DDiameterColumnFeatureValue
    self.diameters = self._calculateCDiameters()
  File "D:\Getting_Started_PyCharm\Pyradiomics\radiomics\shape.py", line 143, in _calculateCDiameters
    return cShape.calculate_diameter(self.maskArray, self.pixelSpacing, Ns)
TypeError: function takes exactly 4 arguments (3 given)

FAILED: Traceback (most recent call last):
  File "D:\Getting_Started_PyCharm\Pyradiomics\radiomics\base.py", line 162, in calculateFeatures
    self.featureValues[feature] = getattr(self, 'get%sFeatureValue' % feature)()
  File "D:\Getting_Started_PyCharm\Pyradiomics\radiomics\shape.py", line 356, in getMaximum2DDiameterRowFeatureValue
    self.diameters = self._calculateCDiameters()
  File "D:\Getting_Started_PyCharm\Pyradiomics\radiomics\shape.py", line 143, in _calculateCDiameters
    return cShape.calculate_diameter(self.maskArray, self.pixelSpacing, Ns)
TypeError: function takes exactly 4 arguments (3 given)

FAILED: Traceback (most recent call last):
  File "D:\Getting_Started_PyCharm\Pyradiomics\radiomics\base.py", line 162, in calculateFeatures
    self.featureValues[feature] = getattr(self, 'get%sFeatureValue' % feature)()
  File "D:\Getting_Started_PyCharm\Pyradiomics\radiomics\shape.py", line 318, in getMaximum2DDiameterSliceFeatureValue
    self.diameters = self._calculateCDiameters()
  File "D:\Getting_Started_PyCharm\Pyradiomics\radiomics\shape.py", line 143, in _calculateCDiameters
    return cShape.calculate_diameter(self.maskArray, self.pixelSpacing, Ns)
TypeError: function takes exactly 4 arguments (3 given)

FAILED: Traceback (most recent call last):
  File "D:\Getting_Started_PyCharm\Pyradiomics\radiomics\base.py", line 162, in calculateFeatures
    self.featureValues[feature] = getattr(self, 'get%sFeatureValue' % feature)()
  File "D:\Getting_Started_PyCharm\Pyradiomics\radiomics\shape.py", line 299, in getMaximum3DDiameterFeatureValue
    self.diameters = self._calculateCDiameters()
  File "D:\Getting_Started_PyCharm\Pyradiomics\radiomics\shape.py", line 143, in _calculateCDiameters
    return cShape.calculate_diameter(self.maskArray, self.pixelSpacing, Ns)
TypeError: function takes exactly 4 arguments (3 given)

Traceback (most recent call last):
  File "D:/Getting_Started_PyCharm/Pyradiomics/Feature_Extraction.py", line 36, in <module>
    featureVector = extractor.execute(cropped_image, cropped_mask)
  File "D:\Getting_Started_PyCharm\Pyradiomics\radiomics\featureextractor.py", line 443, in execute
    featureVector.update(self.computeFeatures(inputImage, inputMask, imageTypeName, **inputKwargs))
  File "D:\Getting_Started_PyCharm\Pyradiomics\radiomics\featureextractor.py", line 543, in computeFeatures
    featureClass = self.featureClasses[featureClassName](image, mask, **kwargs)
  File "D:\Getting_Started_PyCharm\Pyradiomics\radiomics\glcm.py", line 109, in __init__
    self._initSegmentBasedCalculation()
  File "D:\Getting_Started_PyCharm\Pyradiomics\radiomics\glcm.py", line 117, in _initSegmentBasedCalculation
    self.P_glcm = self._calculateCMatrix()
  File "D:\Getting_Started_PyCharm\Pyradiomics\radiomics\glcm.py", line 180, in _calculateCMatrix
    self.kwargs.get('force2Ddimension', 0))
TypeError: function takes exactly 4 arguments (6 given)

Process finished with exit code 1
```

Did something change with the last updates? From the error, I understand that it has to do with the input parameters but I don't get what has changed from before.

Thanks a lot guys, I'm really stuck!

**Comment by QiChen2014** [comment]
@tommydino93 I met the same problem several days ago，then I used an original method to solve it. I delete the hole project on my PC completely, and rebuild it... may be there are other good methods...

**Comment by tommydino93** [comment]
Thanks a lot @QiChen2014 !!

That was drastic, but it actually worked!
