### ISSUE TITLE
Confusing error message when mask is just one pixel

### ISSUE THREAD

**Issue by fedorov** [Radiomics/pyradiomics#443]
Reported by Vu Nguyen (SBU), this is the error when mask is defined by a single pixel in a 2d image:
```
Traceback (most recent call last):
  File "/Users/vuhoangnguyen/Desktop/pyradiomics/pyradiomics_debug.py", line 30, in <module>
    featureVector = extractor.execute(im, ma)
  File "/Library/Python/2.7/site-packages/radiomics/featureextractor.py", line 397, in execute
    boundingBox, correctedMask = imageoperations.checkMask(image, mask, **self.settings)
  File "/Library/Python/2.7/site-packages/radiomics/imageoperations.py", line 230, in checkMask
    raise ValueError('mask has too few dimensions (number of dimensions %d, minimum required %d)' % (ndims, minDims))
ValueError: mask has too few dimensions (number of dimensions 0, minimum required 2)
```
Probably we need a more clear error message.

**Comment by JoostJM** [comment]
fixed in 3efae04
