### ISSUE TITLE
SimpleITK unable to be found during textural extraction.

### ISSUE THREAD

**Issue by juliaryann** [Radiomics/pyradiomics#572]
I am trying to run a textural extraction in batch mode through the command prompt window, so I direct it to my CSV file of images, and then I run it, and these exceptions come up:
Traceback (most recent call last):
  File "c:\users\chris\appdata\local\programs\python\python37\lib\site-packages\SimpleITK\SimpleITK.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "c:\users\chris\appdata\local\programs\python\python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\chris\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\chris\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python37\Scripts\pyradiomics.exe\__main__.py", line 5, in <module>
  File "c:\users\chris\appdata\local\programs\python\python37\lib\site-packages\radiomics\__init__.py", line 15, in <module>
    from . import imageoperations
  File "c:\users\chris\appdata\local\programs\python\python37\lib\site-packages\radiomics\imageoperations.py", line 7, in <module>
    import SimpleITK as sitk
  File "c:\users\chris\appdata\local\programs\python\python37\lib\site-packages\SimpleITK\__init__.py", line 1, in <module>
    from .SimpleITK import *
  File "c:\users\chris\appdata\local\programs\python\python37\lib\site-packages\SimpleITK\SimpleITK.py", line 17, in <module>
    _SimpleITK = swig_import_helper()
  File "c:\users\chris\appdata\local\programs\python\python37\lib\site-packages\SimpleITK\SimpleITK.py", line 16, in swig_import_helper
    return importlib.import_module('_SimpleITK')
  File "c:\users\chris\appdata\local\programs\python\python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_SimpleITK'

C:\Users\chris\AppData\Local\Programs\Python\Python37\Scripts>pyradiomics C:\Users\chris\Desktop\Julia's Scans\Scripts\pyrad patients 0-10
Traceback (most recent call last):
  File "c:\users\chris\appdata\local\programs\python\python37\lib\site-packages\SimpleITK\SimpleITK.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "c:\users\chris\appdata\local\programs\python\python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\chris\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\chris\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python37\Scripts\pyradiomics.exe\__main__.py", line 5, in <module>
  File "c:\users\chris\appdata\local\programs\python\python37\lib\site-packages\radiomics\__init__.py", line 15, in <module>
    from . import imageoperations
  File "c:\users\chris\appdata\local\programs\python\python37\lib\site-packages\radiomics\imageoperations.py", line 7, in <module>
    import SimpleITK as sitk
  File "c:\users\chris\appdata\local\programs\python\python37\lib\site-packages\SimpleITK\__init__.py", line 1, in <module>
    from .SimpleITK import *
  File "c:\users\chris\appdata\local\programs\python\python37\lib\site-packages\SimpleITK\SimpleITK.py", line 17, in <module>
    _SimpleITK = swig_import_helper()
  File "c:\users\chris\appdata\local\programs\python\python37\lib\site-packages\SimpleITK\SimpleITK.py", line 16, in swig_import_helper
    return importlib.import_module('_SimpleITK')
  File "c:\users\chris\appdata\local\programs\python\python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_SimpleITK'

I have SimpleITK installed, so there must be another problem causing it to not be able to be found. 

 - OS: Windows
 - Python version: 3.7
 - PyRadiomics version: unsure

**Comment by codecrazer** [comment]
How many python version in your computer? Maybe you have many python version, and the SimpleITK isn't in the loaded version.

**Comment by juliaryann** [comment]
I only have 1 python installed into my computer. Could it be a problem with
where SimpleITK is downloaded to?

**Comment by JoostJM** [comment]
@juliaryann, the problem you're having is different.
As you can read from the stack trace, SimpleITK *is* installed and found by your python interpreter. The problem is that it is unable to load `_SimpleITK`, which is the compile code holding all the SimpleITK c++ code (the python code is just a wrapper linking to the compiled c++ code).

For some reason or other, the newer version of SimpleITK don't play well with python. You can try an older version of SimpleITK by forcing it to that version, e.g. `pip install SimpleITK==0.9.1`

**Comment by JoostJM** [comment]
See also [issue 513](https://github.com/SimpleITK/SimpleITK/issues/513) on the SimpleITK github.
